//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pays_last
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_user
    {
        public int id { get; set; }
        public string Наименование { get; set; }
        public int Количество { get; set; }
        public decimal Цена { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public int Категория { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
